<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="CsvHelper" />
    <PackageReference Include="NPOI" />
    <PackageReference Include="HtmlAgilityPack" />
    <PackageReference Include="HtmlAgilityPack.CssSelectors.NetCore" />
    <PackageReference Include="SkiaSharp" />
  </ItemGroup>

</Project>
